#!/usr/local/bin/python3

import sys
import argparse
import math
import json
import urllib3

class bcolors:
    HEADER = '\033[95m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

#Command-Line Arguments
parser = argparse.ArgumentParser()
parser.add_argument("name", type = str, help = "Instructor's Name")
parser.add_argument('-w', "--web", dest = "openWebpage", action='store_true', help = "Opens instructor webpage")
parser.add_argument('-b', "--basic", dest = "basicMode", action='store_true', help = "Retrieves only basic information (faster, doesn't parse instructor's webpage for average difficulty rating)")
parser.add_argument("-s", "--school", dest = "schoolID", type = int, default = 1350, help="RMP School ID Number")
clArgs = parser.parse_args()

queryUrl = "https://solr-aws-elb-production.ratemyprofessors.com//solr/rmp/select/?solrformat=true&rows=20&wt=json&json.wrf=noCB&callback=noCB&defType=edismax&qf=teacherfirstname_t%5E2000+teacherlastname_t%5E2000+teacherfullname_t%5E2000+autosuggest&bf=pow(total_number_of_ratings_i%2C2.1)&sort=total_number_of_ratings_i+desc&siteName=rmp&rows=20&start=0&fl=pk_id+teacherfirstname_t+teacherlastname_t+total_number_of_ratings_i+averageratingscore_rf+schoolid_s&q=" + clArgs.name + "+AND+schoolid_s%3A" + str(clArgs.schoolID) + "&fq="
rawResponse = urllib3.PoolManager().request("GET", queryUrl).data.decode('utf-8')[5:-1]
jsonResponse = json.loads(rawResponse)

#Quit program if no result found
numResults = jsonResponse["response"]["numFound"]
if(numResults == 0):
    print(bcolors.FAIL + bcolors.BOLD + "ERROR:" + bcolors.ENDC + " No results found for instructor \"" + bcolors.HEADER + ("%s" % clArgs.name) + bcolors.ENDC + "\" at School #" + bcolors.HEADER + ("%d" % clArgs.schoolID) + bcolors.ENDC)
    sys.exit()
elif(numResults > 1):
    print(bcolors.WARNING + bcolors.BOLD + "WARNING:" + bcolors.ENDC + (" Ambiguous query; continue with which result (1-%d, 0 to exit)? " % numResults) + bcolors.ENDC, end = '')
    invalidInput = True
    while(invalidInput):
        resultNumStr = input("")
        try:
            resultNum = int(resultNumStr)
            if(resultNum < 1):
                sys.exit()
            elif(resultNum > numResults):
                print(("Please enter a number between 1 and %d (0 to exit): " % numResults), end = '')
            else:
                #Convert result number to index (i.e. 1 -> 0)
                resultNum = resultNum - 1
                invalidInput = False
        except ValueError as e:
            print("Please enter a valid number (0 to exit): ", end = '')
else:
    resultNum = 0

pkID = jsonResponse["response"]["docs"][resultNum]["pk_id"]
webpageURL = "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=" + str(pkID)

if(clArgs.openWebpage):
    import webbrowser
    webbrowser.open_new_tab(webpageURL)
    sys.exit()


firstName = jsonResponse["response"]["docs"][resultNum]["teacherfirstname_t"]
lastName = jsonResponse["response"]["docs"][resultNum]["teacherlastname_t"]
fullName = firstName + " " + lastName

try:
    avgRating = jsonResponse["response"]["docs"][resultNum]["averageratingscore_rf"]
except KeyError as e:
    print(bcolors.FAIL + bcolors.BOLD + "ERROR:" + bcolors.ENDC + (" %s %s's average rating is not in the RMP database." % (firstName.capitalize(), lastName.capitalize())))
    print("Instructor ID: %d" % pkID)
    sys.exit()
try:
    numRatings = jsonResponse["response"]["docs"][resultNum]["total_number_of_ratings_i"]
except KeyError as e:
    print(bcolors.FAIL + bcolors.BOLD + "ERROR:" + bcolors.ENDC + (" %s %s's total number of ratings is not in the RMP database." % (firstName.capitalize(), lastName.capitalize())))
    print("Instructor ID: %d" % pkID)
    sys.exit()

#Note: This parsing method relies on the ordering of ".grade" elements on RMP's webpage, so it may not work in the future
if(~clArgs.basicMode):
    from bs4 import BeautifulSoup
    import re
    soup = BeautifulSoup(urllib3.PoolManager().request("GET", webpageURL).data, features="lxml")
    difficultyRatingRegex = re.compile('FeedbackItem__FeedbackNumber.*')
    difficultyRating = float(soup.find_all('div', attrs = {"class": difficultyRatingRegex})[1].text.strip())

class colorScales:
    # [Red, Red) [Yellow, Yellow) [Green, Green]; upper limits are EXCLUSIVE
    rating = [0.0, 2.8, 4.0, 5.0]
    # [Green, Green] (Yellow, Yellow] (Red, Red]; upper limits are INCLUSIVE
    difficulty = [0.0, 2.5, 3.5, 5.0]
def colorCode(rating, colorScale, scaleFlipped = False):
    if(scaleFlipped):
        if(rating > colorScale[2]):
            return bcolors.FAIL
        elif(rating > colorScale[1]):
            return bcolors.WARNING
        else:
            return bcolors.OKGREEN
    else:
        if(rating < colorScale[1]):
            return bcolors.FAIL
        elif(rating < colorScale[2]):
            return bcolors.WARNING
        else:
            return bcolors.OKGREEN

#Make output banners responsive to length of instructor's name
bannerSideLength = math.ceil((len(fullName) - 8) / 2.0)
bannerSide = (10 + bannerSideLength) * '='
print(bcolors.BOLD + bannerSide + " Query Result " + bannerSide + bcolors.ENDC)
print("PK ID:\t\t\t%d" % (pkID))

#Highlight instructor name if not exact query match
print("Full Name:\t\t" + ("" if (clArgs.name.lower() == fullName.lower()) else bcolors.HEADER) + fullName + bcolors.ENDC)
print(bcolors.BOLD + bannerSide + " Ratings Info " + bannerSide + bcolors.ENDC)
print("# Ratings:\t\t%d" % numRatings)
print("Avg. Rating:\t\t" + colorCode(avgRating, colorScales.rating) + bcolors.BOLD + "%.1f" % avgRating + bcolors.ENDC)
if(~clArgs.basicMode):
    print("Avg. Difficulty:\t" + colorCode(difficultyRating, colorScales.difficulty, True) + bcolors.BOLD + "%.1f" % difficultyRating + bcolors.ENDC)
