#!/usr/bin/python3

import sys
import argparse
import math
import json
import urllib3

class bcolors:
    HEADER = '\033[95m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

#Command-Line Arguments
parser = argparse.ArgumentParser()
parser.add_argument("name", type = str, help = "Instructor's Name")
parser.add_argument('-w', "--web", dest = "openWebpage", action='store_true', help = "Opens instructor webpage")
parser.add_argument('-b', "--basic", dest = "basicMode", action='store_true', help = "Retrieves only basic information (faster, doesn't parse instructor's webpage for average difficulty rating)")
parser.add_argument("-s", "--school", dest = "schoolID", type = int, default = 1350, help="RMP School ID Number")
clArgs = parser.parse_args()

queryUrl = "https://solr-aws-elb-production.ratemyprofessors.com//solr/rmp/select/?solrformat=true&rows=20&wt=json&json.wrf=noCB&callback=noCB&defType=edismax&qf=teacherfirstname_t%5E2000+teacherlastname_t%5E2000+teacherfullname_t%5E2000+autosuggest&bf=pow(total_number_of_ratings_i%2C2.1)&sort=total_number_of_ratings_i+desc&siteName=rmp&rows=20&start=0&fl=pk_id+teacherfirstname_t+teacherlastname_t+total_number_of_ratings_i+averageratingscore_rf+schoolid_s&q=" + clArgs.name + "+AND+schoolid_s%3A" + str(clArgs.schoolID) + "&fq="
rawResponse = urllib3.PoolManager().request("GET", queryUrl).data.decode('utf-8')[5:-1]
jsonResponse = json.loads(rawResponse)

#Quit program if no result found
if(jsonResponse["response"]["numFound"] == 0):
    print(bcolors.FAIL + bcolors.BOLD + "ERROR:" + bcolors.ENDC + " No results found for instructor \"" + bcolors.HEADER + ("%s" % clArgs.name) + bcolors.ENDC + "\" at School #" + bcolors.HEADER + ("%d" % clArgs.schoolID) + bcolors.ENDC)
    sys.exit()
elif(jsonResponse["response"]["numFound"] > 1):
    print(bcolors.FAIL + bcolors.BOLD + "ERROR:" + bcolors.ENDC + " Ambiguous query; multiple results returned." + bcolors.WARNING + " Continue with first result? " + bcolors.ENDC, end = '')
    continueParse = input("")
    if("n" in continueParse.lower()):
        sys.exit()

pkID = jsonResponse["response"]["docs"][0]["pk_id"]
webpageURL = "https://www.ratemyprofessors.com/ShowRatings.jsp?tid=" + str(pkID)

if(clArgs.openWebpage):
    import webbrowser
    webbrowser.open_new_tab(webpageURL)
    sys.exit()

firstName = jsonResponse["response"]["docs"][0]["teacherfirstname_t"]
lastName = jsonResponse["response"]["docs"][0]["teacherlastname_t"]
fullName = firstName + " " + lastName
avgRating = jsonResponse["response"]["docs"][0]["averageratingscore_rf"]
numRatings = jsonResponse["response"]["docs"][0]["total_number_of_ratings_i"]

#Note: This parsing method relies on the ordering of ".grade" elements on RMP's webpage, so it may not work in the future
if(~clArgs.basicMode):
    from bs4 import BeautifulSoup
    import re
    soup = BeautifulSoup(urllib3.PoolManager().request("GET", webpageURL).data, features="lxml")
    difficultyRating = float(soup.find_all('div', attrs = {"class": "grade"})[2].text.strip())

class colorScales:
    rating = [0.0, 2.8, 4.0, 5.0]
    difficulty = [0.0, 2.5, 3.5, 5.0]
def colorCode(rating, colorScale, scaleFlipped = False):
    if(scaleFlipped):
        if(rating > colorScale[2]):
            return bcolors.FAIL
        elif(rating > colorScale[1]):
            return bcolors.WARNING
        else:
            return bcolors.OKGREEN
    else:
        if(rating < colorScale[1]):
            return bcolors.FAIL
        elif(rating < colorScale[2]):
            return bcolors.WARNING
        else:
            return bcolors.OKGREEN

#Make output banners responsive to length of instructor's name
bannerSideLength = math.ceil((len(fullName) - 8) / 2.0)
bannerSide = (10 + bannerSideLength) * '='
print(bcolors.BOLD + bannerSide + " Query Result " + bannerSide + bcolors.ENDC)
print("PK ID:\t\t\t%d" % (pkID))

#Highlight instructor name if not exact query match
print("Full Name:\t\t" + ("" if (clArgs.name.lower() == fullName.lower()) else bcolors.HEADER) + fullName + bcolors.ENDC)
print(bcolors.BOLD + bannerSide + " Ratings Info " + bannerSide + bcolors.ENDC)
print("# Ratings:\t\t%d" % numRatings)
print("Avg. Rating:\t\t" + colorCode(avgRating, colorScales.rating) + bcolors.BOLD + "%.1f" % avgRating + bcolors.ENDC)
if(~clArgs.basicMode):
    print("Avg. Difficulty:\t" + colorCode(difficultyRating, colorScales.difficulty, True) + bcolors.BOLD + "%.1f" % difficultyRating + bcolors.ENDC)
